### ISSUE TITLE
buildコマンドの引数がandroidでなくapp

### ISSUE THREAD

**Issue by ghost** [tomorrowkey/HelloBazel#1]
READMEファイル記載のある

Build the app
$ bazel build :android
Install the app
$ bazel mobile-install :android

ですが

Build the app
$ bazel build :app
Install the app
$ bazel mobile-install :app

ではないでしょうか？

**Comment by tomorrowkey** [comment]
たしかに〜

**Comment by tomorrowkey** [comment]
fixed

**Comment by tomorrowkey** [comment]
@tiro105  ありがとうございますー
